[package]
name = "materialx-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sxd-document = "0.3.0"
sxd-xpath = "0.4.0"
#num-traits = "0.2.17"